-- Agency Brands Seed Data for Professional Template Feature
-- Comprehensive list of South African Real Estate Agencies

-- Clear existing data and insert fresh
DELETE FROM agency_brands;

-- Insert predefined agency brands (South African Real Estate Agencies)
INSERT INTO agency_brands (name, slug, logo_url, primary_color, secondary_color, accent_color, heading_font, body_font, logo_position, tagline, header_layout, footer_layout, badge_style, is_active, is_featured, display_order) VALUES

-- Major National Brands
(
    'RE/MAX',
    'remax',
    'https://stagefy.co.za/logos/remax.png',
    '#e11d48',
    '#be123c',
    '#f43f5e',
    'Montserrat',
    'Open Sans',
    'top',
    'With You All The Way',
    'extended',
    'standard',
    'pill',
    true,
    true,
    1
),
(
    'Pam Golding Properties',
    'pam-golding',
    'https://stagefy.co.za/logos/pam-golding.png',
    '#1e3a5f',
    '#0f172a',
    '#3b82f6',
    'Playfair Display',
    'Lato',
    'top',
    'The Gold Standard in Property',
    'standard',
    'standard',
    'square',
    true,
    true,
    2
),
(
    'Seeff',
    'seeff',
    'https://stagefy.co.za/logos/seeff.png',
    '#0d9488',
    '#0f766e',
    '#14b8a6',
    'Raleway',
    'Inter',
    'sidebar',
    'Experience the Difference',
    'compact',
    'minimal',
    'rounded',
    true,
    true,
    3
),
(
    'ERA South Africa',
    'era',
    'https://stagefy.co.za/logos/era.png',
    '#7c3aed',
    '#6d28d9',
    '#8b5cf6',
    'Poppins',
    'Open Sans',
    'top',
    'Real Estate Authority',
    'standard',
    'standard',
    'minimal',
    true,
    true,
    4
),
(
    'Harcourts South Africa',
    'harcourts',
    'https://stagefy.co.za/logos/harcourts.png',
    '#ea580c',
    '#c2410c',
    '#f97316',
    'Georgia',
    'Verdana',
    'top',
    'Leading the Way',
    'extended',
    'contact_only',
    'pill',
    true,
    true,
    5
),
(
    'Lew Geffen Sotheby''s International Realty',
    'sothebys',
    'https://stagefy.co.za/logos/sothebys.png',
    '#0f172a',
    '#1e293b',
    '#334155',
    'Didot',
    'Arial',
    'top',
    'Defining the Art of Living',
    'minimal',
    'minimal',
    'square',
    true,
    true,
    6
),
(
    'Century 21 South Africa',
    'century-21',
    'https://stagefy.co.za/logos/century21.png',
    '#16a34a',
    '#15803d',
    '#22c55e',
    'Arial Black',
    'Arial',
    'top',
    'Let Our Family Help Your Family',
    'standard',
    'standard',
    'rounded',
    true,
    true,
    7
),
(
    'Rawson Properties',
    'rawson',
    'https://stagefy.co.za/logos/rawson.png',
    '#0891b2',
    '#0e7490',
    '#06b6d4',
    'Helvetica Neue',
    'Helvetica',
    'top',
    'Family Owned. Client Focused.',
    'compact',
    'standard',
    'minimal',
    true,
    true,
    8
),
(
    'Chas Everitt',
    'chas-everitt',
    'https://stagefy.co.za/logos/chas-everitt.png',
    '#ca8a04',
    '#a16207',
    '#eab308',
    'Trebuchet MS',
    'Tahoma',
    'top',
    'Property Professionals',
    'standard',
    'standard',
    'pill',
    true,
    true,
    9
),

-- Additional Major Agencies
(
    'Knight Frank South Africa',
    'knight-frank',
    'https://stagefy.co.za/logos/knight-frank.png',
    '#1e3a5f',
    '#0f172a',
    '#2563eb',
    'Times New Roman',
    'Arial',
    'top',
    'Global Real Estate Experts',
    'minimal',
    'minimal',
    'square',
    true,
    true,
    10
),
(
    'Aida',
    'aida',
    'https://stagefy.co.za/logos/aida.png',
    '#dc2626',
    '#b91c1c',
    '#ef4444',
    'Georgia',
    'Verdana',
    'top',
    'Your Property Partner',
    'standard',
    'standard',
    'rounded',
    true,
    false,
    11
),
(
    'Anne Porter Properties',
    'anne-porter',
    'https://stagefy.co.za/logos/anne-porter.png',
    '#1e40af',
    '#1e3a8a',
    '#3b82f6',
    'Playfair Display',
    'Georgia',
    'top',
    'Excellence in Real Estate',
    'standard',
    'standard',
    'square',
    true,
    false,
    12
),
(
    'Dogon Group Properties',
    'dogon-group',
    'https://stagefy.co.za/logos/dogon.png',
    '#0d9488',
    '#0f766e',
    '#14b8a6',
    'Montserrat',
    'Open Sans',
    'top',
    'Distinctive Property Marketing',
    'extended',
    'standard',
    'pill',
    true,
    false,
    13
),
(
    'Greeff Properties',
    'greeff',
    'https://stagefy.co.za/logos/greeff.png',
    '#1e3a5f',
    '#0f172a',
    '#3b82f6',
    'Georgia',
    'Arial',
    'top',
    'Your Trusted Property Partner',
    'standard',
    'standard',
    'minimal',
    true,
    false,
    14
),
(
    'Jawitz Properties',
    'jawitz',
    'https://stagefy.co.za/logos/jawitz.png',
    '#0891b2',
    '#0e7490',
    '#06b6d4',
    'Helvetica Neue',
    'Helvetica',
    'top',
    'The Property Professionals',
    'standard',
    'standard',
    'rounded',
    true,
    false,
    15
),
(
    'Maxwell Property',
    'maxwell',
    'https://stagefy.co.za/logos/maxwell.png',
    '#7c3aed',
    '#6d28d9',
    '#8b5cf6',
    'Poppins',
    'Inter',
    'top',
    'Maximizing Your Property Value',
    'compact',
    'minimal',
    'pill',
    true,
    false,
    16
),

-- Regional & Boutique Agencies
(
    'Berman Brothers Properties',
    'berman-brothers',
    'https://stagefy.co.za/logos/berman.png',
    '#1e3a5f',
    '#0f172a',
    '#3b82f6',
    'Playfair Display',
    'Lato',
    'top',
    'Premium Property Services',
    'minimal',
    'minimal',
    'square',
    true,
    false,
    17
),
(
    'Bishops Property Group',
    'bishops',
    'https://stagefy.co.za/logos/bishops.png',
    '#0d9488',
    '#0f766e',
    '#14b8a6',
    'Montserrat',
    'Open Sans',
    'top',
    'Cape Town Property Specialists',
    'standard',
    'standard',
    'rounded',
    true,
    false,
    18
),
(
    'Campbell Property Group',
    'campbell',
    'https://stagefy.co.za/logos/campbell.png',
    '#ea580c',
    '#c2410c',
    '#f97316',
    'Georgia',
    'Verdana',
    'top',
    'Personal Service, Professional Results',
    'standard',
    'standard',
    'minimal',
    true,
    false,
    19
),
(
    'De Properties',
    'de-properties',
    'https://stagefy.co.za/logos/de-properties.png',
    '#dc2626',
    '#b91c1c',
    '#ef4444',
    'Arial Black',
    'Arial',
    'top',
    'Dedicated to Your Property Needs',
    'compact',
    'minimal',
    'pill',
    true,
    false,
    20
),
(
    'Engel & Völkers',
    'engel-volkers',
    'https://stagefy.co.za/logos/engel-volkers.png',
    '#0f172a',
    '#1e293b',
    '#334155',
    'Didot',
    'Arial',
    'top',
    'Passion for Property',
    'minimal',
    'minimal',
    'square',
    true,
    false,
    21
),
(
    'Fine & Country',
    'fine-country',
    'https://stagefy.co.za/logos/fine-country.png',
    '#1e3a5f',
    '#0f172a',
    '#3b82f6',
    'Playfair Display',
    'Georgia',
    'top',
    'Luxury Property Specialists',
    'minimal',
    'minimal',
    'square',
    true,
    false,
    22
),
(
    'Galileo Properties',
    'galileo',
    'https://stagefy.co.za/logos/galileo.png',
    '#7c3aed',
    '#6d28d9',
    '#8b5cf6',
    'Montserrat',
    'Open Sans',
    'top',
    'Reaching New Heights in Property',
    'standard',
    'standard',
    'rounded',
    true,
    false,
    23
),
(
    'Gordon Properties',
    'gordon',
    'https://stagefy.co.za/logos/gordon.png',
    '#0891b2',
    '#0e7490',
    '#06b6d4',
    'Helvetica Neue',
    'Helvetica',
    'top',
    'Your Local Property Expert',
    'standard',
    'standard',
    'minimal',
    true,
    false,
    24
),
(
    'Homenet',
    'homenet',
    'https://stagefy.co.za/logos/homenet.png',
    '#16a34a',
    '#15803d',
    '#22c55e',
    'Arial',
    'Verdana',
    'top',
    'South Africa''s Property Network',
    'standard',
    'standard',
    'pill',
    true,
    false,
    25
),
(
    'Homes of Distinction',
    'homes-distinction',
    'https://stagefy.co.za/logos/homes-distinction.png',
    '#ca8a04',
    '#a16207',
    '#eab308',
    'Georgia',
    'Arial',
    'top',
    'Exceptional Properties, Exceptional Service',
    'minimal',
    'minimal',
    'square',
    true,
    false,
    26
),
(
    'Infinity Properties',
    'infinity',
    'https://stagefy.co.za/logos/infinity.png',
    '#0d9488',
    '#0f766e',
    '#14b8a6',
    'Poppins',
    'Inter',
    'top',
    'Endless Possibilities in Property',
    'compact',
    'minimal',
    'pill',
    true,
    false,
    27
),
(
    'Just Property',
    'just-property',
    'https://stagefy.co.za/logos/just-property.png',
    '#ea580c',
    '#c2410c',
    '#f97316',
    'Montserrat',
    'Open Sans',
    'top',
    'Just the Right Property',
    'standard',
    'standard',
    'rounded',
    true,
    false,
    28
),
(
    'Keller Williams South Africa',
    'keller-williams',
    'https://stagefy.co.za/logos/keller-williams.png',
    '#dc2626',
    '#b91c1c',
    '#ef4444',
    'Arial Black',
    'Arial',
    'top',
    'Real Estate Redefined',
    'extended',
    'standard',
    'pill',
    true,
    false,
    29
),
(
    'Marshall''s Property',
    'marshalls',
    'https://stagefy.co.za/logos/marshalls.png',
    '#1e40af',
    '#1e3a8a',
    '#3b82f6',
    'Georgia',
    'Verdana',
    'top',
    'Trusted Property Advisors',
    'standard',
    'standard',
    'minimal',
    true,
    false,
    30
),
(
    'Meridian Realty',
    'meridian',
    'https://stagefy.co.za/logos/meridian.png',
    '#7c3aed',
    '#6d28d9',
    '#8b5cf6',
    'Playfair Display',
    'Lato',
    'top',
    'Global Reach, Local Expertise',
    'standard',
    'standard',
    'square',
    true,
    false,
    31
),
(
    'Meyer de Waal Properties',
    'meyer-de-waal',
    'https://stagefy.co.za/logos/meyer-de-waal.png',
    '#0f172a',
    '#1e293b',
    '#334155',
    'Times New Roman',
    'Arial',
    'top',
    'Cape Town Property Specialists',
    'minimal',
    'minimal',
    'square',
    true,
    false,
    32
),
(
    'Milton Real Estate',
    'milton',
    'https://stagefy.co.za/logos/milton.png',
    '#0891b2',
    '#0e7490',
    '#06b6d4',
    'Montserrat',
    'Open Sans',
    'top',
    'Your Property Journey Starts Here',
    'compact',
    'minimal',
    'rounded',
    true,
    false,
    33
),
(
    'Momentum Properties',
    'momentum',
    'https://stagefy.co.za/logos/momentum.png',
    '#16a34a',
    '#15803d',
    '#22c55e',
    'Helvetica Neue',
    'Helvetica',
    'top',
    'Moving You Forward',
    'standard',
    'standard',
    'pill',
    true,
    false,
    34
),
(
    'Pam Golding Properties (International)',
    'pam-golding-intl',
    'https://stagefy.co.za/logos/pam-golding-intl.png',
    '#1e3a5f',
    '#0f172a',
    '#3b82f6',
    'Playfair Display',
    'Lato',
    'top',
    'International Property Excellence',
    'minimal',
    'minimal',
    'square',
    true,
    false,
    35
),
(
    'Property 24 (Private Seller)',
    'property24',
    'https://stagefy.co.za/logos/property24.png',
    '#ea580c',
    '#c2410c',
    '#f97316',
    'Arial',
    'Verdana',
    'top',
    'South Africa''s #1 Property Site',
    'compact',
    'minimal',
    'pill',
    true,
    false,
    36
),
(
    'PropHunter',
    'prophunter',
    'https://stagefy.co.za/logos/prophunter.png',
    '#dc2626',
    '#b91c1c',
    '#ef4444',
    'Poppins',
    'Inter',
    'top',
    'Hunt for Your Dream Home',
    'standard',
    'standard',
    'rounded',
    true,
    false,
    37
),
(
    'Realty One',
    'realty-one',
    'https://stagefy.co.za/logos/realty-one.png',
    '#0d9488',
    '#0f766e',
    '#14b8a6',
    'Montserrat',
    'Open Sans',
    'top',
    'One Stop Property Solutions',
    'standard',
    'standard',
    'minimal',
    true,
    false,
    38
),
(
    'RE/MAX Elite',
    'remax-elite',
    'https://stagefy.co.za/logos/remax-elite.png',
    '#e11d48',
    '#be123c',
    '#f43f5e',
    'Montserrat',
    'Open Sans',
    'top',
    'Elite Service, Elite Results',
    'extended',
    'standard',
    'pill',
    true,
    false,
    39
),
(
    'RE/MAX Premier',
    'remax-premier',
    'https://stagefy.co.za/logos/remax-premier.png',
    '#e11d48',
    '#be123c',
    '#f43f5e',
    'Montserrat',
    'Open Sans',
    'top',
    'Premier Property Services',
    'extended',
    'standard',
    'pill',
    true,
    false,
    40
),
(
    'Ruth Properties',
    'ruth',
    'https://stagefy.co.za/logos/ruth.png',
    '#ca8a04',
    '#a16207',
    '#eab308',
    'Georgia',
    'Arial',
    'top',
    'Dedicated to Excellence',
    'standard',
    'standard',
    'square',
    true,
    false,
    41
),
(
    'Safri Properties',
    'safri',
    'https://stagefy.co.za/logos/safri.png',
    '#1e40af',
    '#1e3a8a',
    '#3b82f6',
    'Helvetica Neue',
    'Helvetica',
    'top',
    'Your African Property Partner',
    'standard',
    'standard',
    'rounded',
    true,
    false,
    42
),
(
    'Sakha Property Group',
    'sakha',
    'https://stagefy.co.za/logos/sakha.png',
    '#7c3aed',
    '#6d28d9',
    '#8b5cf6',
    'Poppins',
    'Inter',
    'top',
    'Building Dreams, Creating Homes',
    'compact',
    'minimal',
    'pill',
    true,
    false,
    43
),
(
    'Samuel Seeff Properties',
    'samuel-seeff',
    'https://stagefy.co.za/logos/samuel-seeff.png',
    '#0d9488',
    '#0f766e',
    '#14b8a6',
    'Raleway',
    'Inter',
    'top',
    'Seeff - Experience the Difference',
    'compact',
    'minimal',
    'rounded',
    true,
    false,
    44
),
(
    'Smiths Property Group',
    'smiths',
    'https://stagefy.co.za/logos/smiths.png',
    '#0891b2',
    '#0e7490',
    '#06b6d4',
    'Montserrat',
    'Open Sans',
    'top',
    'Professional Property Services',
    'standard',
    'standard',
    'minimal',
    true,
    false,
    45
),
(
    'South Coast Property',
    'south-coast',
    'https://stagefy.co.za/logos/south-coast.png',
    '#16a34a',
    '#15803d',
    '#22c55e',
    'Georgia',
    'Verdana',
    'top',
    'Coastal Living Specialists',
    'standard',
    'standard',
    'pill',
    true,
    false,
    46
),
(
    'Trafalgar Properties',
    'trafalgar',
    'https://stagefy.co.za/logos/trafalgar.png',
    '#0f172a',
    '#1e293b',
    '#334155',
    'Playfair Display',
    'Lato',
    'top',
    'Managing Property with Pride',
    'minimal',
    'minimal',
    'square',
    true,
    false,
    47
),
(
    'Tyson Properties',
    'tyson',
    'https://stagefy.co.za/logos/tyson.png',
    '#ea580c',
    '#c2410c',
    '#f97316',
    'Arial Black',
    'Arial',
    'top',
    'Dynamic Property Solutions',
    'extended',
    'standard',
    'pill',
    true,
    false,
    48
),
(
    'Wendy Applebaum Properties',
    'wendy-applebaum',
    'https://stagefy.co.za/logos/wendy-applebaum.png',
    '#1e3a5f',
    '#0f172a',
    '#3b82f6',
    'Didot',
    'Arial',
    'top',
    'Luxury Property Portfolio',
    'minimal',
    'minimal',
    'square',
    true,
    false,
    49
),
(
    'Wingate Properties',
    'wingate',
    'https://stagefy.co.za/logos/wingate.png',
    '#dc2626',
    '#b91c1c',
    '#ef4444',
    'Montserrat',
    'Open Sans',
    'top',
    'Your Property Investment Partner',
    'standard',
    'standard',
    'rounded',
    true,
    false,
    50
),
(
    'Yellow Dot Properties',
    'yellow-dot',
    'https://stagefy.co.za/logos/yellow-dot.png',
    '#ca8a04',
    '#a16207',
    '#eab308',
    'Poppins',
    'Inter',
    'top',
    'Spot On Property Solutions',
    'compact',
    'minimal',
    'pill',
    true,
    false,
    51
),
(
    'Other / Independent',
    'other',
    NULL,
    '#64748b',
    '#475569',
    '#94a3b8',
    'Inter',
    'Inter',
    'top',
    'Independent Agent',
    'standard',
    'standard',
    'minimal',
    true,
    false,
    99
);

-- Note: Replace logo_url values with actual agency logo URLs in production
-- These are placeholder URLs for demonstration purposes
