-- Agency Brands Seed Data for Professional Template Feature
-- Phase 1: Foundation

-- Insert predefined agency brands
INSERT INTO agency_brands (name, slug, logo_url, primary_color, secondary_color, accent_color, heading_font, body_font, logo_position, tagline, header_layout, footer_layout, badge_style, is_active, is_featured, display_order) VALUES
(
    'RE/MAX',
    'remax',
    'https://example.com/logos/remax.png',
    '#e11d48',
    '#be123c',
    '#f43f5e',
    'Montserrat',
    'Open Sans',
    'top',
    'With You All The Way',
    'extended',
    'standard',
    'pill',
    true,
    true,
    1
),
(
    'Pam Golding Properties',
    'pam-golding',
    'https://example.com/logos/pam-golding.png',
    '#1e3a5f',
    '#0f172a',
    '#3b82f6',
    'Playfair Display',
    'Lato',
    'top',
    'The Gold Standard in Property',
    'standard',
    'standard',
    'square',
    true,
    true,
    2
),
(
    'Seeff',
    'seeff',
    'https://example.com/logos/seeff.png',
    '#0d9488',
    '#0f766e',
    '#14b8a6',
    'Raleway',
    'Inter',
    'sidebar',
    'Experience the Difference',
    'compact',
    'minimal',
    'rounded',
    true,
    true,
    3
),
(
    'ERA South Africa',
    'era',
    'https://example.com/logos/era.png',
    '#7c3aed',
    '#6d28d9',
    '#8b5cf6',
    'Poppins',
    'Open Sans',
    'top',
    'Real Estate Authority',
    'standard',
    'standard',
    'minimal',
    true,
    false,
    4
),
(
    'Harcourts South Africa',
    'harcourts',
    'https://example.com/logos/harcourts.png',
    '#ea580c',
    '#c2410c',
    '#f97316',
    'Georgia',
    'Verdana',
    'top',
    'Leading the Way',
    'extended',
    'contact_only',
    'pill',
    true,
    false,
    5
),
(
    'Lew Geffen Sotheby''s International Realty',
    'sothebys',
    'https://example.com/logos/sothebys.png',
    '#0f172a',
    '#1e293b',
    '#334155',
    'Didot',
    'Arial',
    'top',
    'Defining the Art of Living',
    'minimal',
    'minimal',
    'square',
    true,
    true,
    6
),
(
    'Century 21 South Africa',
    'century-21',
    'https://example.com/logos/century21.png',
    '#16a34a',
    '#15803d',
    '#22c55e',
    'Arial Black',
    'Arial',
    'top',
    'Let Our Family Help Your Family',
    'standard',
    'standard',
    'rounded',
    true,
    false,
    7
),
(
    'Rawson Properties',
    'rawson',
    'https://example.com/logos/rawson.png',
    '#0891b2',
    '#0e7490',
    '#06b6d4',
    'Helvetica Neue',
    'Helvetica',
    'top',
    'Family Owned. Client Focused.',
    'compact',
    'standard',
    'minimal',
    true,
    false,
    8
),
(
    'Chas Everitt',
    'chas-everitt',
    'https://example.com/logos/chas-everitt.png',
    '#ca8a04',
    '#a16207',
    '#eab308',
    'Trebuchet MS',
    'Tahoma',
    'top',
    'Property Professionals',
    'standard',
    'standard',
    'pill',
    true,
    false,
    9
),
(
    'Propety Connection',
    'property-connection',
    'https://example.com/logos/property-connection.png',
    '#64748b',
    '#475569',
    '#94a3b8',
    'Segoe UI',
    'Segoe UI',
    'top',
    'Connecting You to Property',
    'compact',
    'minimal',
    'square',
    true,
    false,
    10
);

-- Note: Replace logo_url values with actual agency logo URLs in production
-- These are placeholder URLs for demonstration purposes
