var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/crm/media/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__71d274a2._.js")
R.c("server/chunks/ssr/Documents_Stagefy-V2_5b4205fb._.js")
R.c("server/chunks/ssr/Documents_Stagefy-V2_40ce2d6d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__a7876d27._.js")
R.c("server/chunks/ssr/[root-of-the-server]__eb9e8eb1._.js")
R.c("server/chunks/ssr/16284_next_dist_e9dfbbaf._.js")
R.c("server/chunks/ssr/Documents_Stagefy-V2_src_app_2b087080._.js")
R.c("server/chunks/ssr/Documents_Stagefy-V2_src_app_global-error_tsx_fc909d6b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7077e2a9._.js")
R.c("server/chunks/ssr/Documents_Stagefy-V2_src_app_loading_tsx_14bd204c._.js")
R.c("server/chunks/ssr/16284_next_dist_client_components_68d77977._.js")
R.c("server/chunks/ssr/16284_next_dist_client_components_builtin_forbidden_13ba6b19.js")
R.c("server/chunks/ssr/16284_next_dist_client_components_builtin_unauthorized_5c864b31.js")
R.c("server/chunks/ssr/Documents_Stagefy-V2_src_app_crm_layout_tsx_c48c15d1._.js")
R.c("server/chunks/ssr/Documents_Stagefy-V2__next-internal_server_app_crm_media_page_actions_bd429a1a.js")
R.m(27111)
module.exports=R.m(27111).exports
