// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/billing" | "/billing/cancelled" | "/billing/success" | "/calendar" | "/crm" | "/crm/calendar" | "/crm/contacts" | "/crm/listings" | "/crm/media" | "/dashboard" | "/description-generator" | "/forgot-password" | "/image-to-video" | "/login" | "/onboarding" | "/photo-edit" | "/reset-password" | "/settings" | "/shop" | "/shop/[id]" | "/shop/cart" | "/shop/checkout" | "/shop/payment/cancelled" | "/shop/payment/success" | "/signup" | "/templates"
type AppRouteHandlerRoutes = "/api/admin/usage" | "/api/agent-profile" | "/api/ai/content-plan" | "/api/ai/description-generator" | "/api/ai/image-to-video" | "/api/ai/photo-edit" | "/api/ai/template" | "/api/ai/template/generate-prompt" | "/api/ai/template/layout" | "/api/brands" | "/api/calendar/events" | "/api/calendar/events/[id]" | "/api/content/calendar" | "/api/content/calendar/[id]" | "/api/content/publish/facebook" | "/api/content/publish/instagram" | "/api/crm/activities" | "/api/crm/contacts" | "/api/crm/contacts/[id]" | "/api/crm/listings" | "/api/crm/listings/[id]" | "/api/crm/tasks" | "/api/cron/monthly-reset" | "/api/cron/publish-scheduled" | "/api/dashboard/stats" | "/api/notifications" | "/api/notifications/read" | "/api/payments/cancel" | "/api/payments/create" | "/api/payments/webhook" | "/api/shop/orders" | "/api/shop/payment" | "/api/shop/payment/notify" | "/api/shop/products" | "/api/social/accounts" | "/api/social/accounts/[platform]" | "/api/social/accounts/callback" | "/api/upload/image"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/billing" | "/crm" | "/dashboard" | "/description-generator" | "/image-to-video" | "/photo-edit" | "/settings" | "/shop" | "/templates"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/api/admin/usage": {}
  "/api/agent-profile": {}
  "/api/ai/content-plan": {}
  "/api/ai/description-generator": {}
  "/api/ai/image-to-video": {}
  "/api/ai/photo-edit": {}
  "/api/ai/template": {}
  "/api/ai/template/generate-prompt": {}
  "/api/ai/template/layout": {}
  "/api/brands": {}
  "/api/calendar/events": {}
  "/api/calendar/events/[id]": { "id": string; }
  "/api/content/calendar": {}
  "/api/content/calendar/[id]": { "id": string; }
  "/api/content/publish/facebook": {}
  "/api/content/publish/instagram": {}
  "/api/crm/activities": {}
  "/api/crm/contacts": {}
  "/api/crm/contacts/[id]": { "id": string; }
  "/api/crm/listings": {}
  "/api/crm/listings/[id]": { "id": string; }
  "/api/crm/tasks": {}
  "/api/cron/monthly-reset": {}
  "/api/cron/publish-scheduled": {}
  "/api/dashboard/stats": {}
  "/api/notifications": {}
  "/api/notifications/read": {}
  "/api/payments/cancel": {}
  "/api/payments/create": {}
  "/api/payments/webhook": {}
  "/api/shop/orders": {}
  "/api/shop/payment": {}
  "/api/shop/payment/notify": {}
  "/api/shop/products": {}
  "/api/social/accounts": {}
  "/api/social/accounts/[platform]": { "platform": string; }
  "/api/social/accounts/callback": {}
  "/api/upload/image": {}
  "/billing": {}
  "/billing/cancelled": {}
  "/billing/success": {}
  "/calendar": {}
  "/crm": {}
  "/crm/calendar": {}
  "/crm/contacts": {}
  "/crm/listings": {}
  "/crm/media": {}
  "/dashboard": {}
  "/description-generator": {}
  "/forgot-password": {}
  "/image-to-video": {}
  "/login": {}
  "/onboarding": {}
  "/photo-edit": {}
  "/reset-password": {}
  "/settings": {}
  "/shop": {}
  "/shop/[id]": { "id": string; }
  "/shop/cart": {}
  "/shop/checkout": {}
  "/shop/payment/cancelled": {}
  "/shop/payment/success": {}
  "/signup": {}
  "/templates": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/billing": never
  "/crm": never
  "/dashboard": never
  "/description-generator": never
  "/image-to-video": never
  "/photo-edit": never
  "/settings": never
  "/shop": never
  "/templates": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
