// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(landing)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(landing)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/billing/cancelled/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/billing/cancelled">> = Specific
  const handler = {} as typeof import("../../src/app/billing/cancelled/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/billing">> = Specific
  const handler = {} as typeof import("../../src/app/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/billing/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/billing/success">> = Specific
  const handler = {} as typeof import("../../src/app/billing/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/crm/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/crm/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/crm/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/crm/contacts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/crm/contacts">> = Specific
  const handler = {} as typeof import("../../src/app/crm/contacts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/crm/listings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/crm/listings">> = Specific
  const handler = {} as typeof import("../../src/app/crm/listings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/crm/media/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/crm/media">> = Specific
  const handler = {} as typeof import("../../src/app/crm/media/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/crm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/crm">> = Specific
  const handler = {} as typeof import("../../src/app/crm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/description-generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/description-generator">> = Specific
  const handler = {} as typeof import("../../src/app/description-generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/image-to-video/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/image-to-video">> = Specific
  const handler = {} as typeof import("../../src/app/image-to-video/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/photo-edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/photo-edit">> = Specific
  const handler = {} as typeof import("../../src/app/photo-edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/shop/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/shop/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/shop/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/cart">> = Specific
  const handler = {} as typeof import("../../src/app/shop/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/shop/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/shop/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/shop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop">> = Specific
  const handler = {} as typeof import("../../src/app/shop/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/shop/payment/cancelled/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/payment/cancelled">> = Specific
  const handler = {} as typeof import("../../src/app/shop/payment/cancelled/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/shop/payment/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/payment/success">> = Specific
  const handler = {} as typeof import("../../src/app/shop/payment/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../src/app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates">> = Specific
  const handler = {} as typeof import("../../src/app/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/usage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/usage">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/usage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent-profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent-profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent-profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/content-plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/content-plan">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/content-plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/description-generator/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/description-generator">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/description-generator/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/image-to-video/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/image-to-video">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/image-to-video/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/photo-edit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/photo-edit">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/photo-edit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/template/generate-prompt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/template/generate-prompt">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/template/generate-prompt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/template/layout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/template/layout">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/template/layout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/template/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/template">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/template/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/brands/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/brands">> = Specific
  const handler = {} as typeof import("../../src/app/api/brands/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/calendar/events/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar/events/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/calendar/events/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/calendar/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar/events">> = Specific
  const handler = {} as typeof import("../../src/app/api/calendar/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/content/calendar/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content/calendar/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/content/calendar/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/content/calendar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/api/content/calendar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/content/publish/facebook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content/publish/facebook">> = Specific
  const handler = {} as typeof import("../../src/app/api/content/publish/facebook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/content/publish/instagram/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content/publish/instagram">> = Specific
  const handler = {} as typeof import("../../src/app/api/content/publish/instagram/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/crm/activities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crm/activities">> = Specific
  const handler = {} as typeof import("../../src/app/api/crm/activities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/crm/contacts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crm/contacts/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/crm/contacts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/crm/contacts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crm/contacts">> = Specific
  const handler = {} as typeof import("../../src/app/api/crm/contacts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/crm/listings/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crm/listings/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/crm/listings/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/crm/listings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crm/listings">> = Specific
  const handler = {} as typeof import("../../src/app/api/crm/listings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/crm/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crm/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/api/crm/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/monthly-reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/monthly-reset">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/monthly-reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/publish-scheduled/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/publish-scheduled">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/publish-scheduled/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/read">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/cancel">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/create">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/shop/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shop/orders">> = Specific
  const handler = {} as typeof import("../../src/app/api/shop/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/shop/payment/notify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shop/payment/notify">> = Specific
  const handler = {} as typeof import("../../src/app/api/shop/payment/notify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/shop/payment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shop/payment">> = Specific
  const handler = {} as typeof import("../../src/app/api/shop/payment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/shop/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shop/products">> = Specific
  const handler = {} as typeof import("../../src/app/api/shop/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/social/accounts/[platform]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/accounts/[platform]">> = Specific
  const handler = {} as typeof import("../../src/app/api/social/accounts/[platform]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/social/accounts/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/accounts/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/social/accounts/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/social/accounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/accounts">> = Specific
  const handler = {} as typeof import("../../src/app/api/social/accounts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upload/image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload/image">> = Specific
  const handler = {} as typeof import("../../src/app/api/upload/image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(landing)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(landing)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/billing/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/billing">> = Specific
  const handler = {} as typeof import("../../src/app/billing/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/crm/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/crm">> = Specific
  const handler = {} as typeof import("../../src/app/crm/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/description-generator/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/description-generator">> = Specific
  const handler = {} as typeof import("../../src/app/description-generator/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/image-to-video/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/image-to-video">> = Specific
  const handler = {} as typeof import("../../src/app/image-to-video/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/photo-edit/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/photo-edit">> = Specific
  const handler = {} as typeof import("../../src/app/photo-edit/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/shop/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/shop">> = Specific
  const handler = {} as typeof import("../../src/app/shop/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/templates/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/templates">> = Specific
  const handler = {} as typeof import("../../src/app/templates/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
